export PROMPT_CONFIG_UPDATES ?= true
export HTTPS_MODE = false
export SIMPLE := simply-expanded
override OPT = forced
override export STACKED := both
FOO := 1
export FOO
unexport FOO
undefine GONE
all:
	@echo done
.PHONY: all
